spring.application.name=ethervault-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ethervault
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=55d21c435a2973715e7b2f67462a4d4b3b284c4a4e4d462c4b57442d4a52422e
jwt.expiration=3600000

# Pinata IPFS Configuration
pinata.api.key=7853b43fa58a8e470499
pinata.api.secret=c2b7f3ebaab0c1f2703cc72d4b3bd4fc9e565e637e217d73b8892018f5eadb52

# Polygon Amoy Configuration (Public & Reliable)
polygon.rpc.url=https://rpc-amoy.polygon.technology
polygon.contract.address=0x4f3B6c6C0e75e857C7781aE32B4129E954e4d9b1
polygon.private.key=12e6c55297f3e0db586234999dacc0ef7ee5bc9b047fa99a9e73c05258fac116
polygon.chain.id=80002
blockchain.events.enabled=true

# Multipart Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
